@startuml memory_trainer_use_case

left to right direction
skinparam monochrome true
skinparam usecase {
  BackgroundColor #F9F9F9
  BorderColor #333333
}

actor "Player" as User <<Human>>

rectangle "Memory Trainer" {
  usecase "Auth" as UC1
  usecase "Registration" as UC2
  usecase "Start training session" as UC3
  usecase "Check the progress" as UC4
  usecase "Check the leaderboard" as UC5
  
  User --> UC1
  User --> UC2
  User --> UC3
  User --> UC4
  User --> UC5
}

' Расширенные сценарии
usecase "Get the difficulty" as UC6
usecase "Remember the sequence" as UC7
usecase "Enter the answer" as UC8
usecase "Get the result" as UC9

UC3 --> UC6
UC3 --> UC7
UC3 --> UC8
UC3 --> UC9

@enduml