find_path(POSTGRESQL_INCLUDE_DIR
  NAMES libpq-fe.h
  PATHS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include
)

find_library(POSTGRESQL_LIBRARY
  NAMES pq libpq
  PATHS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PostgreSQL DEFAULT_MSG
  POSTGRESQL_LIBRARY
  POSTGRESQL_INCLUDE_DIR
)

if(POSTGRESQL_FOUND)
  set(POSTGRESQL_LIBRARIES ${POSTGRESQL_LIBRARY})
  set(POSTGRESQL_INCLUDE_DIRS ${POSTGRESQL_INCLUDE_DIR})
  
  if(NOT TARGET PostgreSQL::PQ)
    add_library(PostgreSQL::PQ UNKNOWN IMPORTED)
    set_target_properties(PostgreSQL::PQ PROPERTIES
      IMPORTED_LOCATION "${POSTGRESQL_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${POSTGRESQL_INCLUDE_DIR}"
      INTERFACE_LINK_LIBRARIES "OpenSSL::SSL;ws2_32;secur32"
    )
  endif()
endif()
