name: CI Build

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg install openssl:x64-windows-static libpq:x64-windows-static
        
    - name: Build with MinGW
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
        cmake --build build --config Release

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpq-dev \
          libssl-dev \
          openssl \
          g++ \
          cmake \
          postgresql-server-dev-all
    
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
          -DOPENSSL_ROOT_DIR=/usr \
          -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql
        cmake --build build --config Release